version: '3.2'
services:
  rawrepoDb:
    image: docker-metascrum.artifacts.dbccloud.dk/rawrepo-postgres-1.15-snapshot:DIT-5165
    environment:
      - POSTGRES_DB=rawrepo
      - POSTGRES_USER=rawrepo
      - POSTGRES_PASSWORD=thePassword
    ports:
      - "5432"

  updateserviceDb:
    image: docker-metascrum.artifacts.dbccloud.dk/update-postgres:latest
    environment:
      - POSTGRES_DB=updateservice
      - POSTGRES_USER=updateservice
      - POSTGRES_PASSWORD=thePassword
    ports:
      - "5432"

  fakeSmtp:
    image: docker-externals.artifacts.dbccloud.dk/fakesmtp
    volumes:
      - "../../../docker/logs/fakesmtp:/output"

  updateservice:
    image: docker-metascrum.artifacts.dbccloud.dk/update-payara-dev:latest
    env_file:
      - settings.env
      - db.env
      - providers.env
    environment:
      - VIPCORE_ENDPOINT=${DEV_VIPCORE_ENDPOINT}
      - INSTANCE_NAME=${USER}_dev
      - OPENNUMBERROLL_URL=${DEV_NUMBERROLL_URL}
      - IDP_SERVICE_URL=${DEV_IDP_SERVICE_URL}
      - JAVA_MAX_HEAP_SIZE=8G
      - RAWREPO_DB_URL=${DEV_RAWREPO_DB_URL}
      - UPDATE_DB_URL=${DEV_UPDATE_DB_URL}
      - SOLR_URL=${DEV_SOLR_URL}
      - SOLR_BASIS_URL=${DEV_SOLR_BASIS_URL}
      - OPENCAT_BUSINESS_URL=${DEV_OPENCAT_BUSINESS_URL}
      - HOLDING_ITEMS_CONTENT_SERVICE_URL=${DEV_HOLDINGS_URL}
    extra_hosts:
      - "solrserver:${HOST_IP}"
      - "solrbasis:${HOST_IP}"
    ports:
      - "8080"
      - "8686"
      - "4848"

  updateservice-facade:
    image: docker-metascrum.artifacts.dbccloud.dk/updateservice-facade:master-34
    environment:
      - UPDATE_SERVICE_URL=${UPDATE_SERVICE_URL}
      - BUILD_SERVICE_URL=${BUILD_SERVICE_URL}
      - JAVA_MAX_HEAP_SIZE=2G
    ports:
      - "8080"
      - "8686"
      - "4848"

  opencat-business-service:
    image: docker-metascrum.artifacts.dbccloud.dk/opencat-business:latest
    environment:
      - VIPCORE_ENDPOINT=${DEV_VIPCORE_ENDPOINT}
      - RAWREPO_RECORD_SERVICE_URL=${DEV_RAWREPO_RECORD_SERVICE_URL}
      - OPENNUMBERROLL_URL=${DEV_NUMBERROLL_URL}
      - SOLR_BASIS_URL=${DEV_SOLR_BASIS_URL}
      - SOLR_URL=${DEV_SOLR_URL}
      - INSTANCE_NAME=${USER}_dev
      - JAVA_MAX_HEAP_SIZE=2G
      - JAVASCRIPT_POOL_SIZE=1
    volumes:
      - "../../../../opencat-business:/opt/payara5/deployments/opencat-business"
    extra_hosts:
      - "solrserver:${HOST_IP}"
      - "solrbasis:${HOST_IP}"
    ports:
      - "8080"
      - "8686"
      - "4848"

  rawrepo-record-service:
    image: docker-metascrum.artifacts.dbccloud.dk/rawrepo-record-service:DIT-349
    environment:
      -  INSTANCE_NAME=${USER}_dev
      -  VIPCORE_ENDPOINT=${DEV_VIPCORE_ENDPOINT}
      -  RAWREPO_URL=${DEV_RAWREPO_DB_URL}
      -  HOLDING_ITEMS_CONTENT_SERVICE_URL=${DEV_HOLDINGS_URL}
      -  JAVA_MAX_HEAP_SIZE=2G
    ports:
      - "8080"
      - "8686"
      - "4848"
