version: '3.2'
networks:
  default:
    external:
      name: update-compose-network

services:

  rawrepoDb:
    image: docker-io.dbc.dk/rawrepo-postgres-1.13-snapshot:DIT-5016
    environment:
      - POSTGRES_DB=rawrepo
      - POSTGRES_USER=rawrepo
      - POSTGRES_PASSWORD=thePassword
    ports:
      - "5432"

  holdingsitemsDb:
    image: docker-os.dbc.dk/holdings-items-postgres-1.1.4:latest
    environment:
      - POSTGRES_DB=holdingsitems
      - POSTGRES_USER=holdingsitems
      - POSTGRES_PASSWORD=thePassword
    ports:
      - "5432"

  updateserviceDb:
    image: docker-i.dbc.dk/update-postgres:latest
    environment:
      - POSTGRES_DB=updateservice
      - POSTGRES_USER=updateservice
      - POSTGRES_PASSWORD=thePassword
    ports:
      - "5432"

  fakeSmtp:
    image: docker-i.dbc.dk/fakesmtp
    volumes:
      - "../../../docker/logs/fakesmtp:/output"

  updateservice:
    image: docker-i.dbc.dk/update-payara-dev:latest
    env_file:
      - settings.env
      - db.env
      - providers.env
    environment:
      - OPENAGENCY_URL=${DEV_OPENAGENCY_URL}
      - INSTANCE_NAME=${USER}_dev
      - OPENNUMBERROLL_URL=${DEV_NUMBERROLL_URL}
      - JAVA_MAX_HEAP_SIZE=8G
      - RAWREPO_DB_URL=${DEV_RAWREPO_DB_URL}
      - HOLDINGS_ITEMS_DB_URL=${DEV_HOLDINGS_ITEMS_DB_URL}
      - UPDATE_DB_URL=${DEV_UPDATE_DB_URL}
      - SOLR_URL=${DEV_SOLR_URL}
      - SOLR_BASIS_URL=${DEV_SOLR_BASIS_URL}
      - OPENCAT_BUSINESS_URL=${DEV_OPENCAT_BUSINESS_URL}
    extra_hosts:
      - "solrserver:${HOST_IP}"
      - "solrbasis:${HOST_IP}"
    volumes:
      - "../../../../opencat-business:/opt/payara5/deployments/opencat-business"
    ports:
      - "8080"
      - "8686"
      - "4848"

  updateservice-facade:
    image: docker-io.dbc.dk/updateservice-facade:master-31
    environment:
      - UPDATE_SERVICE_URL=${UPDATE_SERVICE_URL}
      - BUILD_SERVICE_URL=${BUILD_SERVICE_URL}
      - JAVA_MAX_HEAP_SIZE=2G
    ports:
      - "8080"
      - "8686"
      - "4848"

  opencat-business-service:
    image: docker-io.dbc.dk/opencat-business:latest
    environment:
      - OPENAGENCY_URL=${DEV_OPENAGENCY_URL}
      - RAWREPO_RECORD_SERVICE_URL=${DEV_RAWREPO_RECORD_SERVICE_URL}
      - OPENNUMBERROLL_URL=${DEV_NUMBERROLL_URL}
      - SOLR_BASIS_URL=${DEV_SOLR_BASIS_URL}
      - SOLR_URL=${DEV_SOLR_URL}
      - INSTANCE_NAME=${USER}_dev
      - JAVA_MAX_HEAP_SIZE=2G
      - JAVASCRIPT_POOL_SIZE=1
    volumes:
      - "../../../../opencat-business:/opt/payara5/deployments/opencat-business"
    extra_hosts:
      - "solrserver:${HOST_IP}"
      - "solrbasis:${HOST_IP}"
    ports:
      - "8080"
      - "8686"
      - "4848"

  rawrepo-record-service:
    image: docker-io.dbc.dk/rawrepo-record-service:DIT-271
    environment:
      -  INSTANCE_NAME=${USER}_dev
      -  OPENAGENCY_URL=${DEV_OPENAGENCY_URL}
      -  RAWREPO_URL=${DEV_RAWREPO_DB_URL}
      -  HOLDINGS_URL=${DEV_HOLDINGS_ITEMS_DB_URL}
      -  JAVA_MAX_HEAP_SIZE=2G
    ports:
      - "8080"
      - "8686"
      - "4848"
