update-fbs:
  build: .
  dockerfile: Dockerfile
  environment:
    - POSTGRES_DB=rawrepo
    - POSTGRES_USER=rawrepo
    - POSTGRES_PASSWORD=thePassword
  ports:
    - "18280:8080"
    - "18248:4848"
